# Generated by Django 5.2.3 on 2025-10-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('indoor', 'Indoor Plants'), ('outdoor', 'Outdoor Plants'), ('flowering', 'Flowering Plants'), ('fruit', 'Fruit Plants'), ('others', 'Other Plants')], default='others', max_length=50),
        ),
    ]
