# Generated by Django 5.2.3 on 2025-10-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('flowering', 'Flowering'), ('fruit', 'Fruit'), ('others', 'Other Plants')], default='others', max_length=50),
        ),
    ]
